services:
  server:
    build:
      context: .
      dockerfile: Dockerfiles/nginx.dockerfile
    ports:
      - '8000:80'
    volumes:
      - ./TMS-Laravel:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
  php:
    build:
      context: .
      dockerfile: Dockerfiles/php.dockerfile
    volumes:
      - ./TMS-Laravel:/var/www/html:delegated
    depends_on:
      - composer

  composer:
    build:
      context: .
      dockerfile: Dockerfiles/composer.dockerfile
    volumes:
      - ./TMS-Laravel:/var/www/html
    working_dir: /var/www/html
  artisan:
    build:
      context: .
      dockerfile: Dockerfiles/php.dockerfile
    volumes:
      - ./TMS-Laravel:/var/www/html
    entrypoint: ['php', '/var/www/html/artisan']
    depends_on:
      - composer
  npm:
    image: node:14
    working_dir: /var/www/html
    entrypoint: ['npm']
    volumes:
      - ./TMS-Laravel:/var/www/html
#  golang:
#    build:
#      context: ./dockerfiles
#      dockerfile: golang.dockerfile
#  mongo:
#    image: mongo
#    restart: always
#    env_file:
#      - ./env/mongo.env
#  mongo-express:
#    image: mongo-express
#    restart: always
#    ports:
#      - "8081:8081"
#    env_file:
#      - ./env/mongo.express.env